document.writeln("<header class=\'sidenav\' id=\'sidenav\'>");
document.writeln("    <!-- Search -->");
document.writeln("    <div class=\'sidenav__search-mobile\'>");
document.writeln("      <form method=\'get\' class=\'sidenav__search-mobile-form\'>");
document.writeln("        <input type=\'search\' class=\'sidenav__search-mobile-input\' placeholder=\'Search...\' aria-label=\'Search input\'>");
document.writeln("        <button type=\'submit\' class=\'sidenav__search-mobile-submit\' aria-label=\'Submit search\'>");
document.writeln("          <i class=\'ui-search\'></i>");
document.writeln("        </button>");
document.writeln("      </form>");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <nav>");
document.writeln("      <ul class=\'sidenav__menu\' role=\'menubar\'>");
document.writeln("        <li>");
document.writeln("          <a href=\'#\' class=\'sidenav__menu-link\'>首頁</a>");
document.writeln("        </li>");
document.writeln("        <li>");
document.writeln("          <a href=\'#\' class=\'sidenav__menu-link\'>萌动态</a>");
document.writeln("        </li>");
document.writeln("        <li>");
document.writeln("          <a href=\'#\' class=\'sidenav__menu-link\'>萌故事</a>");
document.writeln("          <button class=\'sidenav__menu-toggle\' aria-haspopup=\'true\' aria-label=\'Open dropdown\'><i class=\'ui-arrow-down\'></i></button>");
document.writeln("          <ul class=\'sidenav__menu-dropdown\'>");
document.writeln("            <li><a href=\'f1.httml\' class=\'sidenav__menu-link\'>萌福</a></li>");
document.writeln("            <li><a href=\'f2.httml\' class=\'sidenav__menu-link\'>禄禄</a></li>");
document.writeln("            <li><a hre=\'f3.httml\' class=\'sidenav__menu-link\'>寿寿</a></li>");
document.writeln("            <li><a href=\'f4.httml\' class=\'sidenav__menu-link\'>双喜</a></li>");
document.writeln("            <li><a href=\'f1.httml\' class=\'sidenav__menu-link\'>阿财</a></li>");
document.writeln("          </ul>");
document.writeln("        </li>");
document.writeln("      ");
document.writeln("        <li>");
document.writeln("          <a href=\'#\' class=\'sidenav__menu-link\'>萌下载</a>");
document.writeln("          <button class=\'sidenav__menu-toggle\' aria-haspopup=\'true\' aria-label=\'Open dropdown\'><i class=\'ui-arrow-down\'></i></button>");
document.writeln("          <ul class=\'sidenav__menu-dropdown\'>");
document.writeln("            <li><a href=\'#\' class=\'sidenav__menu-link\'>萌神表情包</a></li>");
document.writeln("            <li><a href=\'#\' class=\'sidenav__menu-link\'>萌神壁纸</a></li>");
document.writeln("            <li><a href=\'#\' class=\'sidenav__menu-link\'>萌神皮肤</a></li>");
document.writeln("          </ul>");
document.writeln("        </li>");
document.writeln("");
document.writeln("        <li>");
document.writeln("          <a href=\'#\' class=\'sidenav__menu-link\'>萌漫画</a>");
document.writeln("        </li>");
document.writeln("   ");
document.writeln("        <li>");
document.writeln("          <a href=\'#\' class=\'sidenav__menu-link\'>萌商城</a>");
document.writeln("          <button class=\'sidenav__menu-toggle\' aria-haspopup=\'true\' aria-label=\'Open dropdown\'><i class=\'ui-arrow-down\'></i></button>");
document.writeln("          <ul class=\'sidenav__menu-dropdown\'>");
document.writeln("            <li><a href=\'#\' class=\'sidenav__menu-link\'>萌神周边</a></li>");
document.writeln("            <li><a href=\'#\' class=\'sidenav__menu-link\'>毛绒玩偶</a></li>");
document.writeln("            <li><a href=\'#\' class=\'sidenav__menu-link\'>数码周边</a></li>");
document.writeln("            <li><a href=\'#\' class=\'sidenav__menu-link\'>汽车座套</a></li>");
document.writeln("            <li><a href=\'#\' class=\'sidenav__menu-link\'>装饰品</a></li>");
document.writeln("          </ul>");
document.writeln("        </li>");
document.writeln("      </ul>");
document.writeln("    </nav>");
document.writeln("  </header>");